<?php
namespace Xdecaro\Component\Competitions\Administrator\Helper;

defined('_JEXEC') or die;

use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;

final class PageHeaderHelper
{
    public static function render(string $view, string $layout = 'default', ?int $id = null): string
    {
        LanguageHelper::load();
        $id = max(0, (int) $id);

        $lists = [
            'dashboard' => ['COM_XDECAROCOMPETITIONS_PAGE_COMPETITIONS', 'COM_XDECAROCOMPETITIONS_DASHBOARD', 'COM_XDECAROCOMPETITIONS_PAGE_DASHBOARD_DESC'],
            'organizations' => ['COM_XDECAROCOMPETITIONS_ORGANIZATIONS', 'COM_XDECAROCOMPETITIONS_ORGANIZATIONS', 'COM_XDECAROCOMPETITIONS_PAGE_ORGANIZATIONS_DESC'],
            'zones' => ['COM_XDECAROCOMPETITIONS_ZONES', 'COM_XDECAROCOMPETITIONS_ZONES', 'COM_XDECAROCOMPETITIONS_PAGE_ZONES_DESC'],
            'countries' => ['COM_XDECAROCOMPETITIONS_COUNTRIES', 'COM_XDECAROCOMPETITIONS_COUNTRIES', 'COM_XDECAROCOMPETITIONS_PAGE_COUNTRIES_DESC'],
            'federations' => ['COM_XDECAROCOMPETITIONS_FEDERATIONS', 'COM_XDECAROCOMPETITIONS_FEDERATIONS', 'COM_XDECAROCOMPETITIONS_PAGE_FEDERATIONS_DESC'],
            'tournaments' => ['COM_XDECAROCOMPETITIONS_TOURNAMENTS', 'COM_XDECAROCOMPETITIONS_TOURNAMENTS', 'COM_XDECAROCOMPETITIONS_PAGE_TOURNAMENTS_DESC'],
            'seasons' => ['COM_XDECAROCOMPETITIONS_SEASONS', 'COM_XDECAROCOMPETITIONS_SEASONS', 'COM_XDECAROCOMPETITIONS_PAGE_SEASONS_DESC'],
            'teams' => ['COM_XDECAROCOMPETITIONS_TEAMS', 'COM_XDECAROCOMPETITIONS_TEAMS', 'COM_XDECAROCOMPETITIONS_PAGE_TEAMS_DESC'],
            'participations' => ['COM_XDECAROCOMPETITIONS_PARTICIPATIONS', 'COM_XDECAROCOMPETITIONS_PARTICIPATIONS', 'COM_XDECAROCOMPETITIONS_PAGE_PARTICIPATIONS_DESC'],
            'players' => ['COM_XDECAROCOMPETITIONS_PLAYERS', 'COM_XDECAROCOMPETITIONS_PLAYERS', 'COM_XDECAROCOMPETITIONS_PAGE_PLAYERS_DESC'],
            'rosters' => ['COM_XDECAROCOMPETITIONS_ROSTERS', 'COM_XDECAROCOMPETITIONS_ROSTERS', 'COM_XDECAROCOMPETITIONS_PAGE_ROSTERS_DESC'],
            'matches' => ['COM_XDECAROCOMPETITIONS_MATCHES', 'COM_XDECAROCOMPETITIONS_MATCHES', 'COM_XDECAROCOMPETITIONS_PAGE_MATCHES_DESC'],
            'information' => ['COM_XDECAROCOMPETITIONS', 'COM_XDECAROCOMPETITIONS_INFORMATION', 'COM_XDECAROCOMPETITIONS_PAGE_INFORMATION_DESC'],
        ];

        $forms = [
            'organization' => ['COM_XDECAROCOMPETITIONS_ORGANIZATIONS', 'COM_XDECAROCOMPETITIONS_ORGANIZATION_NEW', 'COM_XDECAROCOMPETITIONS_ORGANIZATION_EDIT', 'COM_XDECAROCOMPETITIONS_PAGE_ORGANIZATIONS_DESC'],
            'zone' => ['COM_XDECAROCOMPETITIONS_ZONES', 'COM_XDECAROCOMPETITIONS_ZONE_NEW', 'COM_XDECAROCOMPETITIONS_ZONE_EDIT', 'COM_XDECAROCOMPETITIONS_PAGE_ZONES_DESC'],
            'country' => ['COM_XDECAROCOMPETITIONS_COUNTRIES', 'COM_XDECAROCOMPETITIONS_COUNTRY_NEW', 'COM_XDECAROCOMPETITIONS_COUNTRY_EDIT', 'COM_XDECAROCOMPETITIONS_PAGE_COUNTRIES_DESC'],
            'federation' => ['COM_XDECAROCOMPETITIONS_FEDERATIONS', 'COM_XDECAROCOMPETITIONS_FEDERATION_NEW', 'COM_XDECAROCOMPETITIONS_FEDERATION_EDIT', 'COM_XDECAROCOMPETITIONS_PAGE_FEDERATIONS_DESC'],
            'tournament' => ['COM_XDECAROCOMPETITIONS_TOURNAMENTS', 'COM_XDECAROCOMPETITIONS_TOURNAMENT_NEW', 'COM_XDECAROCOMPETITIONS_TOURNAMENT_EDIT', 'COM_XDECAROCOMPETITIONS_PAGE_TOURNAMENTS_DESC'],
            'season' => ['COM_XDECAROCOMPETITIONS_SEASONS', 'COM_XDECAROCOMPETITIONS_SEASON_NEW', 'COM_XDECAROCOMPETITIONS_SEASON_EDIT', 'COM_XDECAROCOMPETITIONS_PAGE_SEASONS_DESC'],
            'team' => ['COM_XDECAROCOMPETITIONS_TEAMS', 'COM_XDECAROCOMPETITIONS_TEAM_NEW', 'COM_XDECAROCOMPETITIONS_TEAM_EDIT', 'COM_XDECAROCOMPETITIONS_PAGE_TEAMS_DESC'],
            'participation' => ['COM_XDECAROCOMPETITIONS_PARTICIPATIONS', 'COM_XDECAROCOMPETITIONS_PARTICIPATION_NEW', 'COM_XDECAROCOMPETITIONS_PARTICIPATION_EDIT', 'COM_XDECAROCOMPETITIONS_PAGE_PARTICIPATIONS_DESC'],
            'player' => ['COM_XDECAROCOMPETITIONS_PLAYERS', 'COM_XDECAROCOMPETITIONS_PLAYER_NEW', 'COM_XDECAROCOMPETITIONS_PLAYER_EDIT', 'COM_XDECAROCOMPETITIONS_PAGE_PLAYERS_DESC'],
            'roster' => ['COM_XDECAROCOMPETITIONS_ROSTERS', 'COM_XDECAROCOMPETITIONS_ROSTER_NEW', 'COM_XDECAROCOMPETITIONS_ROSTER_EDIT', 'COM_XDECAROCOMPETITIONS_PAGE_ROSTERS_DESC'],
            'match' => ['COM_XDECAROCOMPETITIONS_MATCHES', 'COM_XDECAROCOMPETITIONS_MATCH_NEW', 'COM_XDECAROCOMPETITIONS_MATCH_EDIT', 'COM_XDECAROCOMPETITIONS_PAGE_MATCHES_DESC'],
        ];

        if (isset($forms[$view]) && $layout === 'edit') {
            [$eyebrowKey, $newKey, $editKey, $descriptionKey] = $forms[$view];
            $data = [
                'eyebrow' => Text::_($eyebrowKey),
                'title' => Text::_($id > 0 ? $editKey : $newKey),
                'description' => Text::_($descriptionKey),
            ];
        } elseif (isset($lists[$view])) {
            [$eyebrowKey, $titleKey, $descriptionKey] = $lists[$view];
            $data = [
                'eyebrow' => Text::_($eyebrowKey),
                'title' => Text::_($titleKey),
                'description' => Text::_($descriptionKey),
            ];
        } else {
            return '';
        }

        if ($view === 'information') {
            $data['class'] = 'competitions-page-header--information';
        }

        return LayoutHelper::render('page.header', $data, JPATH_COMPONENT_ADMINISTRATOR . '/layouts');
    }
}
